# Generated by Django 3.2 on 2023-07-30 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20230730_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppongCart',
            new_name='ShoppingCart',
        ),
    ]
