# Generated by Django 3.2 on 2023-08-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_follow_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_subscribe',
        ),
    ]
